# Generated by Django 3.1.3 on 2020-11-10 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='receivers',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='sender',
        ),
        migrations.AddField(
            model_name='profile',
            name='handler',
            field=models.CharField(default='xxxxxxxxxxxxxxx', max_length=15, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tweet',
            name='author',
            field=models.ForeignKey(default='xxxxxxxxx', on_delete=django.db.models.deletion.CASCADE, related_name='tweets', to='twitter.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tweet',
            name='likers',
            field=models.ManyToManyField(related_name='likes', to='twitter.Profile'),
        ),
        migrations.AddField(
            model_name='tweet',
            name='mentions',
            field=models.ManyToManyField(related_name='mentions', to='twitter.Profile'),
        ),
        migrations.AddField(
            model_name='tweet',
            name='retweeters',
            field=models.ManyToManyField(related_name='retweets', to='twitter.Profile'),
        ),
    ]
