# Generated by Django 3.1.3 on 2020-11-19 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0005_auto_20201119_1354'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={},
        ),
    ]
