# Generated by Django 3.1.3 on 2020-11-19 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0006_auto_20201119_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtag',
            name='usage_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
